function sFiles = fx_bstReplaceTag( sFiles, tag )
% Process: Add tag: Not defined
%sFiles = bst_process('CallProcess', 'process_add_tag', sFiles, [], ...
%    'tag',           tag, ...
%    'output',        1);  % Add to file name

 % Process: Set name: Not defined
 sFiles = bst_process('CallProcess', 'process_set_comment', sFiles, [], ...
     'tag',           tag, ...
     'isindex',       1);
end