function sFiles = fx_bstSplitRecording( sFilesRecordings, epochduration, condition, baseline )

% Start a new report
sFiles = {};

for i = 1 : numel(sFilesRecordings) 
  bst_process('CallProcess',...
    'process_import_data_time', sFilesRecordings(i), [], ...
    'condition',   condition,...
    'subjectname', sFilesRecordings(i).SubjectName, ...
    'split',       epochduration, ...
    'ignoreshort', 0, ...
    'usectfcomp',  1, ...
    'usessp',      1, ...
    'freq',        [], ...
    'baseline',    baseline);
end

end