function import_EEG = import_besa_dat( cfg )

    import_EEG = pop_importdata(...
        'dataformat','float32le',...
        'nbchan',cfg.number_channels,...
        'data', cfg.filename,...
        'setname', cfg.setname, ...
        'srate', cfg.srate,...
        'pnts',cfg.points_per_trial,...
        'xmin',cfg.xmin,...
        'chanlocs',cfg.channel_file);
    
end